# Generated by Django 4.2 on 2023-05-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tour_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Hotels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(default='', max_length=120)),
                ('city_name', models.CharField(default='', max_length=120)),
                ('address', models.TextField(blank=True, max_length=300)),
                ('start_price', models.TextField(blank=True, max_length=80)),
                ('about', models.TextField(max_length=800)),
                ('hotel_image', models.ImageField(upload_to='pics')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.city')),
            ],
        ),
    ]
