# Generated by Django 4.2 on 2023-05-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_destination_seasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_destinations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_name', models.CharField(default='', max_length=122)),
                ('province_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('long_description', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='pics')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.destination_seasons')),
                ('tour_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tour_type')),
            ],
        ),
    ]
