# Generated by Django 4.2 on 2023-06-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tour_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_destinations',
            name='long_description',
            field=models.TextField(max_length=2500),
        ),
    ]
